# Numpy
2차원 행렬을 list보다 쉽게 관리하고 행결 계산과 관련된 함수들이 들어있는 패키지

### numpy 모듈

In [1]:
import numpy as np
np.__version__

'1.16.5'

### numpy 행렬 생성


In [2]:
# 리스트
list1 = [10,20,30,40,50]
print(type(list1))
list1

<class 'list'>


[10, 20, 30, 40, 50]

In [4]:
# numpy 행렬 만들기
array1 = np.array([10,20,30,40,50])
print(type(array1))
print(array1)

<class 'numpy.ndarray'>
[10 20 30 40 50]


In [5]:
# 행렬 복사
array2 = array1
print(f'array1 id : {id(array1)}')
print(f'array2 id : {id(array2)}')

array3 = array1.copy
print(f'array3 id : {id(array3)}')

array1 id : 2063039391584
array2 id : 2063039391584
array3 id : 2063039336184


In [8]:
array1[0] = 100
print(array1)
print(array2)
print(array3)

[100  20  30  40  50]
[100  20  30  40  50]
<built-in method copy of numpy.ndarray object at 0x000001E056BAE760>


### arange 함수

In [11]:
# 0 ~ 10 - 1
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# 10 ~ 20 - 1
array2 = np.arange(10, 20)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
# 10 ~ 20 -1, 3씩 증가
array3 = np.arange(10,20, 3)
array3

array([10, 13, 16, 19])

In [14]:
# 갯수
cnt1 = len(array1)
print(f'cnt1 = {cnt1}')

print(f'size : {array1.size}')

cnt1 = 10
size : 10


### linspace
주어진 범위를 주어진 수만큼 구간을 나눠 행렬을 생성한다.

In [19]:
# 0 ~ 10 까지의 5개 구간
array1 = np.linspace(0, 10, 5)

In [24]:
# 0 ~ 10가지 5개 구간, 증가량 포함
array2 = np.linspace(0,10,5,retstep=True)
array2

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)

In [25]:
print(array2[0])
print(array2[1])

[ 0.   2.5  5.   7.5 10. ]
2.5


### zeros, ones

In [26]:
# 0으로 채워진 행렬을 만든다.
array1 = np.zeros(10)
array1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
# 1로 채워진 행렬을 만든다.
array2 = np.ones(10)
array2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
# 3행 4열 
array3 = np.zeros((3,4))
array4 = np.ones((3,4))
print(array3)
print(array4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [34]:
array5 = np.zeros((3,4), dtype = 'int')
array6 = np.ones((3,4), dtype = 'int')
print(array5)
print(array6)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


### numpy 행렬의 데이터 타입
numpy 행렬은 같은 타입의 데이터만 담을 수 있다. 만약 서로 다른 타입의 값이 저장되면 관리하는 값들의 형 변환이 자동으로 발생한다.

In [36]:
list1 = [10,11.11, '문자열', True]
list1

[10, 11.11, '문자열', True]

In [44]:
# 논리형
array1 = np.array([True, False])
array1

array([ True, False])

In [45]:
# 논리형, 정수
array11 = np.array([True, False, 1, 0])
array11

array([1, 0, 1, 0])

In [46]:
# 논리형, 정수형, 실수
array2 = np.array([True, False, 1, 0, 1.1, 2.2])
array2

array([1. , 0. , 1. , 0. , 1.1, 2.2])

In [47]:
# 정수, 실수, 논리, 문자열
array3 = np.array([True, False, 1, 0, 1.1, 2.2, '문자열'])
array3

array(['True', 'False', '1', '0', '1.1', '2.2', '문자열'], dtype='<U32')