In [1]:
import numpy as np

### 행렬 정보 파악하기

In [3]:
array1 = np.array([[10,20],[30,40],[50,60]])
array1

array([[10, 20],
       [30, 40],
       [50, 60]])

In [8]:
print(f'array1의 전체 개수 : {array1.size}')
print(f'array1의 행렬 : {array1.shape}') # 튜플로 변환해서 반환
print(f'array1의 행의 수 : {array1.shape[0]}')
print(f'array1의 열의 수 : {array1.shape[1]}')

array1의 전체 개수 : 6
array1의 행렬 : (3, 2)
array1의 행의 수 : 3
array1의 열의 수 : 2


### 행렬 재구성 하기

In [12]:
array1 = np.arange(15)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
array2 = array1.reshape(3, 5)
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
array3 = array2.reshape(array2.size) # 하나만 넣어주면 행으로 정렬된다.
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### True, False 를 통한 데이터 추출

In [16]:
array1 = np.arange(100)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
array2 = (array1 % 5) == 0
array2

array([ True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False])

In [24]:
# [] 안에 넣어준 행렬에서 True나 False 자리에 해당하는 값만 꺼내서 행렬로 만들어 반환해준다.
# 즉, []은 인덱스 기능 외에도 True 자리의 값과 일대일 대응해서 원하는 데이터만 뽑을 수 있다.
# 정확한 원리를 가지고 있자요! ([]의 두 가지 기능)
array3 = array1[array2]
array3

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [25]:
array4 = array1[(array1 % 5) == 0]
array4

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])