In [1]:
import numpy as np

In [2]:
# 두 리스트를 더해주면 하나의 리스트로 합쳐져 반환
list1 = [10,20,30]
list2 = [40,50,60]
list3 = list1 + list2
list3

[10, 20, 30, 40, 50, 60]

In [3]:
# 두 행렬을 더해주면 행렬의 각 자리를 연산한 결과를 담을 행렬을 만들어 반환
array1 = np.array([10,20,30])
array2 = np.array([40,50,60])
array3 = array1 + array2
print(array3)

[50 70 90]


In [4]:
# append 함수를 사용하면 두 행렬을 하나로 합쳐서 반환
array4 = np.append(array1,array2)
array4

array([10, 20, 30, 40, 50, 60])

In [6]:
array5 = np.array([[1,2],[3,4]])
array6 = np.array([[5,6],[7,8]])
print(array5)
print(array6)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [10]:
# 2차원 행렬이라고 하더라도 두 행렬을 합친 1차원 행렬로 만들어 반환
array7 = np.append(array5, array6)
array7

array([ 1,  2,  3,  4,  6,  8, 10, 12])

In [15]:
# axis를 0으로 주면 행으로 합쳐진다.
array9 = np.append(array5, array6, axis=0)
array9

array([[ 1,  2],
       [ 3,  4],
       [ 6,  8],
       [10, 12]])

In [16]:
# axis를 1로 주면 열로 합쳐진다.
array10 = np.append(array5, array6, axis=1)
array10

array([[ 1,  2,  6,  8],
       [ 3,  4, 10, 12]])

### 삭제

In [19]:
array1 = np.array([[1,2,3],[4,5,6]])
# (행렬, 값 인덱스)
array2 = np.delete(array1, 0)
array2

array([2, 3, 4, 5, 6])

In [20]:
# 2차원 행을 1차원 행렬로 재 구성하고 인덱스 0,2,4번을 제거해서 반환
array3 = np.delete(array1, (0,2,4))
array3

array([2, 4, 6])

In [23]:
# 0행 제거
array4 = np.delete(array1, 0, axis=0)
array4

array([[4, 5, 6]])

In [26]:
# 0열 제거
array5 = np.delete(array1, 0, axis=1)
array5

array([[2, 3],
       [5, 6]])