In [29]:
import numpy as np

### 리스트와 비교 (더하기, 곱하기)

In [2]:
list1 = [1,2,3]
list2 = [4,5,6]


list3 = list1 + list2
list4 = list1 * 3

print(list3)
print(list4)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [4]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

array3 = np.append(array1, array2)
array4 = np.repeat(array1, 3)

print(array3)
print(array4)

[1 2 3 4 5 6]
[1 1 1 2 2 2 3 3 3]


### 행렬 연산

In [9]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 // array2)
print(array1 ** array2)
print(array1 % array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[  1  32 729]
[1 2 3]


In [10]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(array1 + 3)
print(array1 - 3)
print(array1 * 3)
print(array1 / 3)
print(array1 // 3)
print(array1 ** 3)
print(array1 % 3)

[4 5 6]
[-2 -1  0]
[3 6 9]
[0.33333333 0.66666667 1.        ]
[0 0 1]
[ 1  8 27]
[1 2 0]


### 행렬 내의 값에 대한 집계

In [16]:
array1 = np.arange(1, 10)

print(f'array1 : {array1}')
print(f'array1의 총합 : {array1.sum()}')
print(f'array1의 평균 : {array1.mean()}')
print(f'array1의 표준편차 : {array1.std()}')
print(f'array1의 누적과정 : {array1.cumsum()}')

array1 : [1 2 3 4 5 6 7 8 9]
array1의 총합 : 45
array1의 평균 : 5.0


In [18]:
array2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])ㅁ
print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

print(array2.mean())
print(array2.mean(axis=0))
print(array2.mean(axis=1))

45
[12 15 18]
[ 6 15 24]
5.0
[4. 5. 6.]
[2. 5. 8.]


In [19]:
# 랜덤 행렬
array1 = np.random.randint(10, size=10)
array1

array([8, 4, 3, 1, 1, 0, 6, 2, 5, 1])

In [21]:
array2 = np.random.randint(1, 46, size=1000)

In [22]:
print(f'최대 : {array2.max()}')
print(f'최소 : {array2.min()}')

최대 : 45
최소 : 1


In [28]:
array1 = np.random.randint(10, size=1000)
# 5보다 큰 숫자들의 개수 총합을 구한다.
array2= array1 > 5
array3= array1[array2]
print(array3.size)
print(array3.sum())
print(array3.mean())


print(array1[array1 > 5].size)
print(array1[array1 > 5].sum())
print(array1[array1 > 5].mean())

389
2892
7.434447300771208
389
2892
7.434447300771208


### 중복제거

In [26]:
array1 = [1,1,2,2,3,3,4,4]
array2 = np.unique(array1)
array2

array([1, 2, 3, 4])